<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.2.1" name="walls3" tilewidth="90" tileheight="90" spacing="1" tilecount="55" columns="11">
 <image source="walls3.png" width="1000" height="454"/>
 <tile id="0" type="wallSolid"/>
 <tile id="1" type="wallBreak1"/>
 <tile id="2" type="wallBreak2"/>
 <tile id="3" type="wallSolid"/>
 <tile id="4" type="wallBreak1"/>
 <tile id="5" type="wallBreak2"/>
 <tile id="6" type="wallSolid"/>
 <tile id="7" type="wallBreak1"/>
 <tile id="8" type="wallBreak2"/>
 <tile id="9" type="wallSolid"/>
 <tile id="11" type="wallSolid"/>
 <tile id="12" type="wallBreak1"/>
 <tile id="13" type="wallBreak2"/>
 <tile id="14" type="wallSolid"/>
 <tile id="15" type="wallBreak1"/>
 <tile id="16" type="wallBreak2"/>
 <tile id="17" type="wallSolid"/>
 <tile id="18" type="wallBreak1"/>
 <tile id="19" type="wallBreak2"/>
 <tile id="20" type="wallBreak1"/>
 <tile id="22" type="wallSolid"/>
 <tile id="23" type="wallBreak1"/>
 <tile id="24" type="wallBreak2"/>
 <tile id="25" type="wallSolid"/>
 <tile id="26" type="wallBreak1"/>
 <tile id="27" type="wallBreak2"/>
 <tile id="28" type="wallSolid"/>
 <tile id="29" type="wallBreak1"/>
 <tile id="30" type="wallBreak2"/>
 <tile id="31" type="wallBreak2"/>
 <tile id="33" type="wallSolid"/>
 <tile id="34" type="wallBreak1"/>
 <tile id="35" type="wallBreak2"/>
 <tile id="36" type="wallSolid"/>
 <tile id="37" type="wallBreak1"/>
 <tile id="38" type="wallBreak2"/>
 <tile id="39" type="wallSolid"/>
 <tile id="40" type="wallBreak1"/>
 <tile id="41" type="wallBreak2"/>
 <tile id="42" type="wallCrumbled"/>
 <tile id="44" type="wallSolid"/>
 <tile id="45" type="wallBreak1"/>
 <tile id="46" type="wallBreak2"/>
 <tile id="47" type="wallSolid"/>
 <tile id="48" type="wallBreak1"/>
 <tile id="49" type="wallBreak2"/>
 <tile id="50" type="wallSolid"/>
 <tile id="51" type="wallBreak1"/>
 <tile id="52" type="wallBreak2"/>
 <tile id="53" type="wallCrumbled"/>
</tileset>
